FinalProject/Models/Cus.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Cus
    {
        public int imageID { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        [DisplayName("Upload File")]

        public string imagePath { get; set; }
        
        public HttpPostedFileBase ImageFile { get; set; }

    }
}

FinalProject/Controllers/CusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.IO;

namespace FinalProject.Controllers
{
    public class CusController : Controller
    {
        private FinalProjectEntities1 db = new FinalProjectEntities1();

        // GET: Cus
        public ActionResult Index()
        {
            return View(db.Cus.ToList());
        }

        // GET: Cus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cus cus = db.Cus.Find(id);
            if (cus == null)
            {
                return HttpNotFound();
            }
            return View(cus);
        }

        // GET: Cus/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cus/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public ActionResult Create(Cus cus)
        {
            string fileName = Path.GetFileNameWithoutExtension(cus.ImageFile.FileName);
            string extension = Path.GetExtension(cus.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            cus.imagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"),fileName);
            cus.ImageFile.SaveAs(fileName);


            if (ModelState.IsValid)
            {
                db.Cus.Add(cus);
                db.SaveChanges();
    
            }
            ModelState.Clear();

            return View();
        }
        //public ActionResult View(int id)
        //{
        //    Cus cusM = new Cus();
        //    cusM = db.Cus.Where(x => x.imageID == id).FirstOrDefault();
        //    return View(cusM);
        //}
        // GET: Cus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cus cus = db.Cus.Find(id);
            if (cus == null)
            {
                return HttpNotFound();
            }
            return View(cus);
        }

        // POST: Cus/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "imageID,title,comment,imagePath")] Cus cus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cus);
        }

        // GET: Cus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cus cus = db.Cus.Find(id);
            if (cus == null)
            {
                return HttpNotFound();
            }
            return View(cus);
        }

        // POST: Cus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cus cus = db.Cus.Find(id);
            db.Cus.Remove(cus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject/Views/Cus/Create.cshtml
@model FinalProject.Models.Cus

@{
    ViewBag.Title = "Create";
}
<div>
    <div class="paddingTop"></div>
</div>
<h2>Create</h2>


@using (Html.BeginForm("Create", "Cus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Cus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.imageID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imageID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imageID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="ImageFile" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalProject/Views/Cus/Delete.cshtml
@model FinalProject.Models.Cus

@{
    ViewBag.Title = "Delete";
}
<div>
    <div class="paddingTop"></div>
</div>
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinalProject/Views/Cus/Details.cshtml
@model FinalProject.Models.Cus

@{
    ViewBag.Title = "Details";
}
<div>
    <div class="paddingTop"></div>
</div>
<h2>Details</h2>

<div>
    <h4>Cus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.imagePath)*@
            <img src="@Url.Content(Model.imagePath)" width="250" height="250" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.imageID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FinalProject/Views/Cus/Edit.cshtml
@model FinalProject.Models.Cus

@{
    ViewBag.Title = "Edit";
}
<div>
    <div class="paddingTop"></div>
</div>
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.imageID)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalProject/Views/Cus/Index.cshtml
@model IEnumerable<FinalProject.Models.Cus>

@{
    ViewBag.Title = "Index";
}
<div>
    <div class="paddingTop"></div>
</div>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imagePath)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.imageID }) |
            @Html.ActionLink("Details", "Details", new { id=item.imageID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.imageID })
        </td>
    </tr>
}

</table>